# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/course_service

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load infrastructure from repo
          command: git clone https://github.com/mp-access/Infrastructure.git
      - run:
          name: Start infrastructure
          command: |
            set -x
            cd Infrastructure
            docker-compose -f keycloak-postgres.yml up -d
            docker ps
            sleep 10
            docker ps
            docker run --network container:idp appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:9999
            cd ..


      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test

      # Stop infrastructure
      - run: docker-compose -f Infrastructure/keycloak-postgres.yml down