# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: jboss/keycloak
        environment:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
        command:
          - "-Djboss.bind.address=0.0.0.0"
          - "-Djboss.http.port=9999"

    working_directory: ~/course_service

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for keycloak
          command: dockerize -wait http://localhost:9999 -timeout 1m

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and push Docker image
          command: |
            docker build -t hoal/$COURSE_SERVICE_IMAGE_NAME:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push hoal/$COURSE_SERVICE_IMAGE_NAME:latest
